version: "3.1"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    command:
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      username is 'sa'
      SA_PASSWORD: "Secret123!"
    volumes:
      - db-data:/
  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data: